-- Organization Table 

CREATE TABLE organizations (
    id SERIAL PRIMARY KEY,
    orgName VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);